#-----------------------------------------------
# config.system.yaml user setting
#
# config.system.default.yamlの値をこのファイルで
# 上書きすることが出来ます。
#-----------------------------------------------

### 例 jQueryのバージョンを切り替える
# jquery_version: 3.6.1 # (3.6.1|3.5.1|3.4.1|2.2.3|2.1.1|2.0.3|1.12.3|1.11.1|1.10.1|1.9.1|1.8.3|1.7.2|1.6.4) 2.xはIE9〜
# jquery_migrate: migrate-3.0.1

### セキュリティ
forbid_direct_access_tpl: /^_/ # off | /^_/  パスのディレクトリまたはファイルがこの正規表現に一致したものは直接表示させない
forbid_tpl_inheritance_when_path_unresolved: on # on | off パス解決に失敗した時、テンプレートを継承しないようにする
forbid_tpl_url_context: on # on | off 読者以下のURLコンテキストのtplを許可しない。（例: https://example.com/news/tpl/custom.html）
allow_tpl_path: [] # forbid_tpl_inheritance_when_path_unresolved や forbid_tpl_url_context が on の場合、除外するパスを設定します。例: [news.html,hoge/custom.html] カンマ区切りで指定

### パフォーマンス
cache_expire: 300 # エントリー以外のキャッシュ有効時間（秒）
cache_expire_entry: 86400 # エントリーのキャッシュ有効時間（秒）
cache_clear_when_post: off # on | off エントリー保存や設定変更時にキャッシュをクリアするか設定
cache_clear_target: all # self | self-descendant | self-ancestor | all キャッシュをクリアするターゲットのブログの決め方を指定
template_cache: on # on | off テンプレートのキャッシュを使用するかどうかを設定（onにするとDEBUG_MODEオフの時、include文内で、特定のグローバル変数しか利用できなくなります。またテンプレート編集した時は、キャッシュクリアの操作が必要です）
const_file_path: off # private/const/pc.php
# webp_support: on # on | off webp画像を生成するかどうかを設定

## 画質
media_client_resize: off # on | off メディアでの画像アップロードで、ブラウザでのリサイズを行うかどうかを設定（onにすると、大きな画像もアップロードできるようになりますが、若干画質が劣化します）
